### ISSUE TITLE
functional web login with invalid length test

### ISSUE THREAD

**Issue by qaviton** [qaviton/test_repository#22]
tests setup:
1) load a url
2) go to login

create test with steps :
3) enter username with invalid length and password
4) click login
5) assert login error

create test with steps :
3) enter username and password with invalid length
4) click login
5) assert login error

create test with steps :
3) enter email  with invalid length and password
4) click login
5) assert login error

**Comment by idanhakimi** [comment]
Done

**Comment by idanhakimi** [comment]
Done
