### ISSUE TITLE
functional web login with missing fields tests

### ISSUE THREAD

**Issue by qaviton** [qaviton/test_repository#25]
create test with steps :
1) load a url
2) go to login
3) skip enter a username
4) enter a password
5) click login
6) assert login error

create test with steps :
1) load a url
2) go to login
3) enter a username
4) skip enter a password
5) click login
6) assert login error

create test with steps :
1) load a url
2) go to login
3) skip enter an email
4) enter a password
5) click login
6) assert login error

create test with steps :
1) load a url
2) go to login
3) enter an email
4) skip enter a password
5) click login
6) assert login error

**Comment by idanhakimi** [comment]
Done

**Comment by idanhakimi** [comment]
Done
